version: '3.8'

services:
  api:
    build: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - MONGODB_URI=mongodb://mongodb:27017/todoapi
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: todoapi
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: