name: Node-CI Test

on:
  push:
    branches: [ "main", "staging", "dev", "change_db" ]
  pull_request:
    branches: [ "main", "staging", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      NODE_ENV: test
      PORT: 3003
      MONGODB_URI: mongodb://127.0.0.1:27017/todoapi
    
    services:
      mongodb:
        image: mongo:7
        env:
          MONGO_INITDB_DATABASE: todoapi
        ports:
          - 27017:27017
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm install

    - name: Wait for MongoDB
      run: |
        while ! nc -z 127.0.0.1 27017; do
          echo 'Waiting for MongoDB...'
          sleep 2
        done
        echo 'MongoDB is ready!'

    - name: Start server in background
      run: |
        nohup npm run start &   
        sleep 10
    
    - name: Run tests
      run: npm test
    
    - name: Build Docker image
      run: docker build -t todo-api .